on:
  push:
    branches:
      - master
name: deploy to mc server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: gamesdal145.bisecthosting.com
          port: 2022
          sftp_only: true
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local_path: ./minecraft/*
          remote_path: ./
          rsyncArgs: --exclude 'mods/watermedia-* --no-owner --no-group -vvv
      - name: 🛜 Rcon Reload
        uses: wolfigster/rcon-action@v1.0.2
        with:
          server: ${{ secrets.Rcon_server }}
          port: 25566
          password: ${{ secrets.Rcon_password }}
          commands: '["reload"]'
